# use purty colors
set-option -g default-terminal "screen-256color"

# enable mouse, for now
set -g mode-mouse on

# rebind prefix to Ctrl-A
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind a send-prefix

setw -g xterm-keys on

# use vim bindings for navigation
setw -g mode-keys vi
set -g status-keys vi
bind-key -t vi-edit Up   history-up
bind-key -t vi-edit Down history-down

# copy to system clipboard
bind -t vi-copy 'v' begin-selection
bind -t vi-copy 'y' copy-pipe "reattach-to-user-namespace pbcopy"

# keep current dir when splitting windows
bind c new-window -c '#{pane_current_path}'
bind-key '"' split-window -v -c '#{pane_current_path}'
bind-key '%' split-window -h -c '#{pane_current_path}'

# don't allow repeats for pane navigation (prevents interfering with bash up-arrow)
bind-key Up    select-pane -U
bind-key Down  select-pane -D
bind-key Left  select-pane -L
bind-key Right select-pane -R

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+
set-option -g default-command "reattach-to-user-namespace -l $SHELL"

# jump to specific panes
bind-key C-c select-window -t 1 \; select-pane -t 2
bind-key C-v select-window -t 0 \; select-pane -t 2
bind-key C-d select-window -t 1 \; select-pane -t 1

